language: php

env:
  global:
    - WORDPRESS_DIR=tmp/wordress WORDPRESS_URL=localhost:8080 DB_USER=root DB_PASSWORD='' DB_NAME=dev DB_HOST=localhost

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: WORDPRESS_VERSION=nightly
    - php: 7.2
      env: WORDPRESS_VERSION=latest
    - php: 7.1
      env: WORDPRESS_VERSION=latest
    - php: 7.0
      env: WORDPRESS_VERSION=latest
    - php: 7.0
      env: WORDPRESS_VERSION=4.8.3
    - php: 7.0
      env: WORDPRESS_VERSION=4.7.7
    - php: 7.0
      env: WORDPRESS_VERSION=4.6.8

cache:
  yarn: true
  directories:
  - vendor
  - $HOME/.composer/cache

deploy:
  on:
    branch: refactor

before_install:
  # disable xDebug.
  - phpenv config-rm xdebug.ini || true
  # update Composer.
  - composer self-update

install:
  # install all composer dependencies.
  - composer install
  # install and configure WordPress.
  - bin/setup-wp.sh
  # setup webserver.
  - bin/setup-server.sh


script:
 # - vendor/bin/phpcs
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=/vendor/inpsyde/php-coding-standards/Inpsyde/ruleset.xml
