language: php

env:
  global:
    - WORDPRESS_DIR=tmp/wordress WORDPRESS_URL=localhost:8080 DB_USER=root DB_PASSWORD='' DB_NAME=dev DB_HOST=localhost

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: nightly
    - php: 7.2
    - php: 7.1
    - php: 7.0

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

branches:
  only:
    refactor

before_install:
  # disable xDebug.
  - phpenv config-rm xdebug.ini || true
  # update Composer.
  - composer self-update

install:
  # install all composer dependencies.
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=vendor/inpsyde/php-coding-standards/Inpsyde/ruleset.xml {src,assets,*.php}
