language: php

matrix:
  fast_finish: true

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

branches:
  only:
    refactor

before_install:
  # disable xDebug.
  - phpenv config-rm xdebug.ini || true
  # update Composer.
  - composer self-update

install:
  # install all composer dependencies.
  - composer install

#script:
#  - vendor/bin/phpunit

jobs:
  include:
  - stage: phpcs
    script: vendor/bin/phpcs --standard=vendor/inpsyde/php-coding-standards/Inpsyde/ruleset.xml {src,assets,*.php}
    php: 7.0
  - stage: phpunit
    script: vendor/bin/phpunit
    php: 7.0
  - stage: phpunit
    script: vendor/bin/phpunit
    php: 7.1
  - stage: phpunit
    script: vendor/bin/phpunit
    php: 7.2
  - stage: phpunit
    script: vendor/bin/phpunit
    php: nightly

allow_failures:
  - stage: phpcs
    script: vendor/bin/phpcs --standard=vendor/inpsyde/php-coding-standards/Inpsyde/ruleset.xml {src,assets,*.php}
    php: 7.0
  - stage: phpunit
    script: vendor/bin/phpunit
    php: nightly
