language: php

env: # important!

stages:
- quality
- test

php:
- 7.0

jobs:
  allow_failures:
  - env: STAGE=quality
  - php: nightly
  include:
  # PHPCS ##################
  - stage: quality
    env: STAGE=quality
    php: '7.1'
    script: vendor/bin/phpcs

  # PHPUnit ################
  - stage: test
    php: '7.1'
    script: vendor/bin/phpunit
  - stage: test
    php: '7.2'
    script: vendor/bin/phpunit
  - stage: test
    php: nightly
    script: vendor/bin/phpunit

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

branches:
  only:
  - refactor

before_install:
# disable xDebug.
- phpenv config-rm xdebug.ini || true
# update Composer.
- composer self-update

install:
# install all composer dependencies.
- composer install
