language: php

env: # important!

matrix:
  fast_finish: true
  include:
    - php: nightly
    - php: 7.2
    - php: 7.1
    - php: 7.0
  allow_failures:
    - php: nightly

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

branches:
  only:
    refactor

before_install:
  # disable xDebug.
  - phpenv config-rm xdebug.ini || true
  # update Composer.
  - composer self-update

install:
  # install all composer dependencies.
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=vendor/inpsyde/php-coding-standards/Inpsyde/ruleset.xml {src,assets,*.php}
